import os
SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL")
SECRET KEY = "0+0t7GuqPudV7xWuW2EtMZ+nGOedNy4SliRWrU3tsuY4XLdwIGJQq01L"

DEBUG = True



FEATURE_FLAGS = {
    "ALLOW_FILE_UPLOAD": True
    
}
